// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxivthxfxzteldlusmxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4aXZ0aHhmeHp0ZWxkbHVzbXh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODMyNTQsImV4cCI6MjA2MTk1OTI1NH0._y5gheyCvvjdr5CBhRnmO0HdtBCdRkoe__Kxt1zVnEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);